apiVersion: provisioning-management.ifs.com/v1
kind: Tenant
metadata:
  labels:
    ifs.com/bg-set: bg2
  name: a20a842b-ea2b-40fa-86c9-f1307c2a1574
spec:
  customerId: nide
  suspended: false
  metadata:
    creationTimestamp: "2025-06-16T15:13:17Z"
    customerCode: nide
    environmentName: cfg
    internal: false
    region: westeurope
    regionAreaCode: eu
    regionShortCode: euwe
    tenantShortId: nidecfg1k50d4d
    umids:
    - a20a842b-ea2b-40fa-86c9-f1307c2a1574
  capabilities:
  - name: afp-certification-delay-prediction.inference
    config: {}
    suspended: false
  requestGeneration: 1
