apiVersion: provisioning-management.ifs.com/v1
kind: Tenant
metadata:
  labels:
    ifs.com/bg-set: bg2
  name: xyz-marees-14
spec:
  customerId: nide
  suspended: false
  metadata:
    creationTimestamp: "2025-05-19T12:26:17Z"
    customerCode: nide
    environmentName: cfg
    region: northeurope
    regionAreaCode: eu
    regionShortCode: euno
    tenantShortId: nidecfg1k2m8r9
    umids:
    - xyz-marees-14
  capabilities:
  - name: wo-generation-automation.invoice
    config: {}
    suspended: false
  requestGeneration: 1
